name: Validate & Release
on:
  push:
    branches:
      - main
    # tags:
    #   - v*
jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  publish-npm:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org/
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
